config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles
  get 'signup', to: 'users#new'
  resources :users, except: [:new] do
    member do
      get 'demote_mod'
      get 'promote_mod'
      get 'promote_admin'
      get 'demote_admin'
    end
    patch :promote_mod
    patch :demote_mod
    patch :promote_admin
    patch :demote_admin
  end
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: {minimum: 3, maximum: 100}
  validates :description, presence: true, length: {minimum: 10, maximum: 5000}
  default_scope {order(updated_at: :desc)}
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def show
  end

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:notice] = "Article was created successfully."
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article was updated successfully."
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    if @article.destroy
      flash[:notice] = "Article was deleted successfully."
      redirect_to articles_path
    else
      flash[:notice] = "Article could NOT be deleted"
    end
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description, category_ids: [])
  end

  def require_same_user
    if current_user != @article.user && (!current_user.mod? && !current_user.admin? && !current_user.owner?)
      flash[:alert] = "You can only edit or delete your own article"
      redirect_to @article
    end
  end
end

app/views/articles/_article.html.erb
<div class="container">
  <% @articles.each do |article| %>
    <div class="row justify-content-center">
      <div class="col-6 m-4">
        <div class="card text-center shadow m-6 bg-body rounded">
          <div class="card-header fst-italic">
            <% if article.user %>
              by <span class="admin-color"> <%= "(Admin)" if article.user.admin? %>
              <span class="mod-color"> <%= "(Mod)" if article.user.mod? %>
              <span class="owner-color"> <%= "(Owner)" if article.user.owner? %>
              <%= link_to article.user.username, user_path(article.user) %>
              </span></span></span>
              <td><div class="container text-center", "img-fluid">
                <%= link_to gravatar_for(article.user, size: 50), article.user %>
                <% if article.categories.any? %>
                <br />
                  <%= render article.categories %>
                <% end %>
              </div></td>
            <% end %>
          </div>
          <div class="card-body">
            <h5 class="card-title"><td><%= link_to article.title, article_path(article), class: "text-success" %></td></h5>
            <p class="card-text"> <td><%= truncate(article.description, length: 100) %></td></p>
            <%= link_to "View", article_path(article), class: "btn btn-outline-success" %>
            <% if logged_in? && (article.user == current_user || current_user.admin? || current_user.mod? || current_user.owner?) %>
              <%= link_to "Edit", edit_article_path(article), class: "btn btn-outline-info" %>
            <% end %>
            <% if logged_in? && (article.user == current_user || current_user.admin? || current_user.owner?) %>
              <%= link_to "Delete", article_path(article), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small>Created  <%= time_ago_in_words(article.created_at) %> ago,
            edited <%= time_ago_in_words(article.updated_at) %> ago </small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/articles/_form.html.erb
<div class="container" content="width=device-width,initial-scale=1">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', obj: @article %>
      <%= form_with(model: @article, class: "shadow p-3 mb-3 bg-dark rounded", local: true) do |f| %>

      <div class="input-group row mb-3">
        <%= f.label :title, class: "col-sm-2 col-form-label text-light" %>
        <div class="col-10">
          <%= f.text_field :title, class: "form-control shadow rounded", placeholder: "Title of article"  %>
        </div>
      </div>

      <div class="input-group row mb-3">
        <%= f.label :description, class: "col-sm-2 col-form-label text-light" %>
        <div class="col-10">
          <%= f.text_area :description, rows: 10, class: "form-control shadow rounded", placeholder: "Description of article" %>
        </div>
      </div>

      <div class="input-group row mb-3">
        <%= f.label :category, class: "col-sm-2 col-form-label text-light" %>
        <div class="col-10">
        <%= f.collection_select(:category_ids, Category.all, :id, :name,
        { prompt: "Make your selection(s) from the list (can be empty, hold CTRL to select multiple, or drag mouse)" }, { multiple: true, size: 3, class: "form-select shadow rounded" }) %>
        </div>
      </div>

      <div class="input-group justify-content-center m-3">
        <%= f.submit class: "btn btn-outline-light btn-lg" %>
      </div>

      <% end %>
      <div class="text-center m-3">
        <%= link_to 'Cancel and return to articles listing', articles_path, class: "text-info" %>
      </div>
    </div>
  </div>
</div>

app/views/articles/edit.html.erb
<h1 class="text-center p-3">Edit Article</h1>
<%= render 'form' %>

app/views/articles/index.html.erb
<h1 class="text-center p-3">Listing All Articles</h1>
<div class="flickr_pagination">
  <%= will_paginate @articles, :container => false %>
</div>
<%= render 'article' %>
<div class="flickr_pagination">
  <%= will_paginate @articles, :container => false %>
</div>

app/views/articles/new.html.erb
<h1 class="text-center p-3">Create a new Article</h1>
<%= render 'form' %>

app/views/articles/show.html.erb
<h2 class="text-center p-3"><%= @article.title %></h2>
<div class="container">
    <div class="row justify-content-center">
      <div class="col-6 m-4">
        <div class="card text-center shadow m-6 bg-body rounded">
          <div class="card-header fst-italic">
            by <span class="admin-color"> <%= "(Admin)" if @article.user.admin? %>
            <span class="mod-color"> <%= "(Mod)" if @article.user.mod? %>
            <span class="owner-color"> <%= "(Owner)" if @article.user.owner? %>
            <%= link_to @article.user.username, user_path(@article.user) if @article.user %>
            </span></span></span>
            <br />
            <%= link_to gravatar_for(@article.user), user_path(@article.user) %>
            <% if @article.categories.any? %>
            <br />
              <%= render @article.categories %>
            <% end %>
          </div>
          <div class="card-body">
            <div class="card-text text-start"> <td><%= simple_format(@article.description) %></td></div>
            <% if logged_in? && (@article.user == current_user || current_user.admin? || current_user.mod || current_user.owner?) %>
              <%= link_to "Edit", edit_article_path(@article), class: "btn btn-outline-info" %>
            <% end %>
            <% if logged_in? && (@article.user == current_user || current_user.admin? || current_user.owner?) %>
              <%= link_to "Delete", article_path(@article), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small>Created  <%= time_ago_in_words(@article.created_at) %> ago,
            edited <%= time_ago_in_words(@article.updated_at) %> ago </small>
          </div>
        </div>
      </div>
    </div>
    <div class="text-center m-3">
      <%= link_to 'Cancel and return to articles listing', articles_path, class: "text-info" %>
    </div>
</div>