config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles
  get 'signup', to: 'users#new'
  resources :users, except: [:new] do
    member do
      get 'demote_mod'
      get 'promote_mod'
      get 'promote_admin'
      get 'demote_admin'
    end
    patch :promote_mod
    patch :demote_mod
    patch :promote_admin
    patch :demote_admin
  end
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  before_save { self.username = username.downcase }
  has_many :articles, dependent: :destroy
  validates :username, presence: true,
                       uniqueness: { case_sensitive: false },
                       length: { minimum: 3, maximum: 25 }
  default_scope {order(created_at: :desc)}

  VALID_EMAIL_REGEX = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  validates :email, presence: true,
                    uniqueness: { case_sensitive: false },
                    length: {minimum: 6, maximum: 105 },
                    format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :set_user, only: [:show, :edit, :update, :destroy]
before_action :require_user, only: [:edit, :update]
before_action :require_same_user, only: [:edit, :update, :destroy]
before_action :require_admin, only: [:promote_mod, :demote_mod]
before_action :require_owner, only: [:promote_admin, :demote_admin]

  def show
    @articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end

  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome to the G Blog, #{@user.username}, you're now signed up!"
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "Your account information was successfully updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    if @user.destroy
      session[:user_id] = nil if @user == current_user
      flash[:notice] = "Account and all associated articles successfully deleted"
      redirect_to articles_path
    else
    flash[:notice] = "User could NOT be deleted"
    end
  end

  def demote_mod
    @user = User.find(params[:user_id])
    @user.mod = false
    @user.save
    redirect_to user_path(@user)
  end

  def promote_mod
    @user = User.find(params[:user_id])
    @user.mod = true
    @user.save
    redirect_to user_path(@user)
  end

  def demote_admin
    @user = User.find(params[:user_id])
    @user.admin = false
    @user.save
    redirect_to user_path(@user)
  end

  def promote_admin
    @user = User.find(params[:user_id])
    @user.admin = true
    @user.save
    redirect_to user_path(@user)
  end

  private

  def user_params
  params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user && (!current_user.admin? && !current_user.owner?)
      flash[:alert] = "You can only edit or delete your own account"
      redirect_to @user
    end
  end

  def require_admin
    if !(logged_in? && (current_user.admin? || current_user.owner?))
      flash[:alert] = "Only admins can perform that action"
      redirect_to users_path
    end
  end

  def require_owner
    if !(logged_in? && current_user.owner?)
      flash[:alert] = "Only owners can perform that action"
      redirect_to users_path
    end
  end

end

app/views/users/_form.html.erb
<div class="container" content="width=device-width,initial-scale=1">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', obj: @user %>
      <%= form_with(model: @user, class: "shadow p-3 bg-dark rounded", local: true) do |f| %>

      <div class="input-group row mb-3">
        <%= f.label :username, class: "col-sm-2 col-form-label text-light" %>
        <div class="col-10">
          <%= f.text_field :username, class: "form-control shadow rounded", placeholder: "Enter a username"  %>
        </div>
      </div>

      <div class="input-group row mb-3">
        <%= f.label :email, class: "col-sm-2 col-form-label text-light" %>
        <div class="col-10">
          <%= f.email_field :email, class: "form-control shadow rounded", placeholder: "Enter your email address" %>
        </div>
      </div>

      <div class="input-group row mb-3">
        <%= f.label :password, class: "col-sm-2 col-form-label text-light" %>
        <div class="col-10">
          <%= f.password_field :password, class: "form-control shadow rounded", placeholder: "Choose a password" %>
        </div>
      </div>

      <div class="input-group justify-content-center m-3">
        <%= f.submit(@user.new_record? ? "Sign Up" : "Update Account", class: "btn btn-outline-light btn-lg") %>
      </div>

      <% end %>
      <div class="text-center m-3">
        <%= link_to 'Cancel and return to users listing', users_path, class: "text-info" %>
      </div>
    </div>
  </div>
</div>

app/views/users/_users.html.erb
<div class="container">
  <% @users.each do |user| %>
    <div class="row justify-content-center">
      <div class="col-6 m-4">
        <div class="card text-center shadow m-6 bg-body rounded">
          <div class="card-header fst-italic">
            <span class="admin-color"> <%= "(Admin)" if user.admin? %>
            <span class="mod-color"> <%= "(Mod)" if user.mod? %>
            <span class="owner-color"> <%= "(Owner)" if user.owner? %>
            <%= link_to user.username, user %> </span> </span> </span>
          </div>
          <div class="card-body">
            <td><div class="container text-center", "img-fluid">
              <%= link_to gravatar_for(user, size: 100), user %>
            </div></td>
            <p class="card-text"> <td><%= pluralize(user.articles.count, "article") %></td></p>
            <%= link_to "View Profile", user_path(user), class: "btn btn-outline-success" %>
            <% if logged_in? %>
              <% if user == current_user || current_user.admin? || current_user.owner? %>
                <%= link_to "Edit Profile", edit_user_path(user), class: "btn btn-outline-info" %>
              <% end %>
              <% if current_user.admin? || current_user.owner? %>
                <%= link_to "Delete Account", user_path(user), class: "btn btn-outline-danger", method: :delete,
                data: {confirm: "Are you sure you want to delete this account and all associated articles?"} %>
              <% end %>
            <% end %>

          </div>
          <div class="card-footer text-muted">
            <small>Joined  <%= time_ago_in_words(user.created_at) %> ago </small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<h1 class="text-center p-3">Edit Profile</h1>
<%= render 'form' %>

app/views/users/index.html.erb
<h1 class="text-center p-3">Listing All Users</h1>
<div class="flickr_pagination">
  <%= will_paginate @users, :container => false %>
</div>
<%= render 'users' %>
<div class="flickr_pagination">
  <%= will_paginate @users, :container => false %>
</div>

app/views/users/new.html.erb
<h1 class="text-center p-3">Sign up for the blog</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<h1 class="text-center p-3"><%= "(Admin) " if @user.admin? %><%= "(Mod) " if @user.mod? %><%= "(Owner) " if @user.owner? %><%= @user.username %>'s Profile</h1>
<div class="container text-center", "img-fluid">
  <%= gravatar_for @user, size: 200 %>
</div>
<div class="container text-center mt-4">
  <% if logged_in? && (@user == current_user || current_user.admin? || current_user.owner?) %>
    <%= link_to "Edit your profile", edit_user_path(@user), class: "btn btn-info" %>
    <br />
    <br />
    <%= link_to "Delete Account", user_path(@user), class: "btn btn-outline-danger", method: :delete,
    data: {confirm: "Are you sure you want to delete this account and all associated articles?"} %>
  <% end %>

</div>

<div class="container text-center mt-4">
  <% if logged_in? && current_user.owner? %>
    <%= link_to "Promote Admin", promote_admin_user_path(@user), method: :patch, class: "btn btn-warning" %>
    <br />
    <br />
  <% end %>
  <% if logged_in? && current_user.owner? %>
    <%= link_to "Demote Admin", demote_admin_user_path(@user), method: :patch, class: "btn btn-warning" %>
    <br />
    <br />
  <% end %>
  <% if logged_in? && (current_user.admin? || current_user.owner?) %>
    <%= link_to "Promote Mod", promote_mod_user_path(@user), method: :patch, class: "btn btn-warning" %>
    <br />
    <br />
  <% end %>
  <% if logged_in? && (current_user.admin? || current_user.owner?) %>
    <%= link_to "Demote Mod", demote_mod_user_path(@user), method: :patch, class: "btn btn-warning" %>
    <br />
    <br />
  <% end %>

</div>

<div class="container text-center mt-4">

</div>

<h3 class="text-center p-3">Articles</h3>

<div class="flickr_pagination">
  <%= will_paginate @articles, :container => false %>
</div>

<%= render 'articles/article' %>

<div class="flickr_pagination">
  <%= will_paginate @articles, :container => false %>
</div>