config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles
  get 'signup', to: 'users#new'
  resources :users, except: [:new] do
    member do
      get 'demote_mod'
      get 'promote_mod'
      get 'promote_admin'
      get 'demote_admin'
    end
    patch :promote_mod
    patch :demote_mod
    patch :promote_admin
    patch :demote_admin
  end
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories
end

app/models/category.rb
class Category < ApplicationRecord
 validates :name, presence: true,
                  length: { minimum: 3, maximum: 25 }
 validates_uniqueness_of :name
 has_many :article_categories
 has_many :articles, through: :article_categories
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update]
  before_action :require_admin, except: [:index, :show]
  before_action :require_mod, except: [:index, :show]

  def show
    @articles = @category.articles.paginate(page: params[:page], per_page: 5)
  end

  def index
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Category was successfully created"
      redirect_to @category
    else
      render 'new'
    end
  end

  def update
    if @category.update(category_params)
      flash[:notice] = "Category was updated successfully."
      redirect_to @category
    else
      render 'edit'
    end
  end

  # def destroy
  #   if @category.destroy
  #     flash[:notice] = "Category was deleted successfully."
  #     redirect_to categories_path
  #   else
  #     flash[:notice] = "Category could NOT be deleted"
  #   end
  # end



  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    if !(logged_in? && (current_user.admin? || current_user.owner?))
      flash[:alert] = "Only admins can perform that action"
      redirect_to categories_path
    end
  end

  def require_mod
    if !(logged_in? && (current_user.admin? || current_user.mod? || current_user.owner?))
      flash[:alert] = "Only mods can perform that action"
      redirect_to categories_path
    end
  end
end

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), class: "badge rounded-pill bg-info text-dark" %>

app/views/categories/_form.html.erb
<div class="container" content="width=device-width,initial-scale=1">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', obj: @category %>
      <%= form_with(model: @category, class: "shadow p-3 bg-dark rounded", local: true) do |f| %>

      <div class="input-group row mb-3">
        <%= f.label :name, "Category Name", class: "col-sm-2 col-form-label text-light" %>
        <div class="col-10">
          <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "Enter a category name"  %>
        </div>
      </div>


      <div class="input-group justify-content-center m-3">
        <%= f.submit class: "btn btn-outline-light btn-lg" %>
      </div>

      <% end %>
    </div>
  </div>
</div>

app/views/categories/edit.html.erb
<h1 class="text-center p-3">Edit Category</h1>
<%= render 'form' %>
<div class="text-center m-3">
  <%= link_to 'Cancel and return to category', category_path(@category), class: "text-info" %>
</div>

app/views/categories/index.html.erb
<h1 class="text-center p-3">Listing All Categories</h1>
<div class="flickr_pagination">
  <%= will_paginate @categories, :container => false %>
</div>
<div class="container">
  <% @categories.each do |category| %>
    <div class="row justify-content-center">
      <div class="col-4 m-4">
        <div class="card text-center shadow m-6 bg-body rounded">
          <div class="card-body">
            <h5 class="card-title"><td><%= link_to category.name, category_path(category), class: "text-success" %></td></h5>
            <p class="card-text"> <td><%= pluralize(category.articles.count, "article") %></td></p>
            <% if logged_in? && current_user.admin? %>
              <%= link_to "Edit", edit_category_path(category), class: "btn btn-outline-info" %>
              <%# <%= link_to "Delete", category_path(category), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small>Created  <%= time_ago_in_words(category.created_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>
<div class="flickr_pagination">
  <%= will_paginate @categories, :container => false %>
</div>

app/views/categories/new.html.erb
<h1 class="text-center p-3">Create a new Category</h1>
<%= render 'form' %>
<div class="text-center m-3">
  <%= link_to 'Cancel and return to categories listing', categories_path, class: "text-info" %>
</div>

app/views/categories/show.html.erb
<h1 class="text-center p-3">Category: <%= @category.name %></h1>

<div class="container text-center mt-4">
  <% if logged_in? && current_user.admin? %>
    <%= link_to "Edit Category Name", edit_category_path(@category), class: "btn btn-info" %>
  <% end %>
</div>

<h3 class="text-center p-3">Articles</h3>

<div class="flickr_pagination">
  <%= will_paginate @articles, :container => false %>
</div>

<%= render 'articles/article' %>

<div class="flickr_pagination">
  <%= will_paginate @articles, :container => false %>
</div>