config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles
  get 'signup', to: 'users#new'
  resources :users, except: [:new] do
    member do
      get 'demote_mod'
      get 'promote_mod'
      get 'promote_admin'
      get 'demote_admin'
    end
    patch :promote_mod
    patch :demote_mod
    patch :promote_admin
    patch :demote_admin
  end
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories
end

app/views/layouts/_footer.html.erb
<div class="container-fluid fixed-bottom bg-dark">
  <div class="container-fluid">
    <p class="navbar-brand text-center text-white fs-6 m-1" id="footer">Copyright ©Gary McQueen</p>
  </div>
</div>

app/views/layouts/_jumbotron.html.erb
<div class="container">
  <div class="text-white p-5 rounded-pill m-5 text-center jumbo-bg">
    <h1 class="display-4">G Blog</h1>
    <p class="lead">Vertical on cell phones in portrait, horizontal in landscape.</p>
    <hr class="my-4"></hr>
    <p>Sign up below to post your own <%= link_to "Articles", articles_path %>! </p>
    <p>You do not need to verify an email to join, just enter a fake email in valid format
       then you can post articles!</p>
    <%= link_to "Sign up!", signup_path, class: "btn btn-success btn-lg" %>
  </div>
</div>

app/views/layouts/_messages.html.erb
<div class="container">
<% flash.each do |name, msg| %>
  <% if name = notice %>
    <div class="alert alert-success alert-dismissible fade show d-flex align-items-center" role="alert">
      <%= msg %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% else %>
    <div class="alert alert-danger alert-dismissible fade show d-flex align-items-center" role="alert">
      <%= msg %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
<% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light">
  <div class="container-fluid">
    <%= link_to "G Blog", root_path, class: "navbar-brand", id: "logo" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Articles
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <% if logged_in? %>
              <li><%= link_to "Create new Article", new_article_path, class: "dropdown-item" %></li>
            <% end %>
            <li><%= link_to "View Articles", articles_path, class: "dropdown-item" %></li>
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Categories
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <% if logged_in? %>
              <li><%= link_to "Create new Category", new_category_path, class: "dropdown-item" %></li>
            <% end %>
            <li><%= link_to "View Categories", categories_path, class: "dropdown-item" %></li>
          </ul>
        </li>
        <li class="nav-item">
          <%= link_to "Users", users_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Can't Touch Me</a>
        </li>
        <% if logged_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= "(Admin)" if current_user.admin? %>
              <%= "(Mod)" if current_user.mod? %>
              <%= "(Owner)" if current_user.owner? %> Profile
              <% if current_user.admin? %>
                <span class="admin-color"> [<%= current_user.username %>] </span>
              <% elsif current_user.mod? %>
                <span class="mod-color"> [<%= current_user.username %>] </span>
              <% elsif current_user.owner? %>
                <span class="owner-color"> [<%= current_user.username %>] </span>
              <% else %>
                [<%= current_user.username %>]
              <% end %>
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><%= link_to "View your profile", user_path(current_user), class: "dropdown-item" %></li>
              <li><%= link_to "Edit your profile", edit_user_path(current_user), class: "dropdown-item" %></li>
              <li><%= link_to "Delete your account", user_path(current_user), class: "dropdown-item text-danger", method: :delete,
              data: {confirm: "Are you sure you want to delete your account and all articles?"} %> </li>
            </ul>
          </li>
          <li class="nav-item">
            <%= link_to "Logout", logout_path, class: "nav-link", method: :delete  %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", login_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign up", signup_path, class: "nav-link" %>
          </li>
        <% end %>
        <li class="nav-item">
          <%= link_to "About", about_path, class: "nav-link" %>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" justify-content-right type="search" placeholder="Not Functional Yet" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>G Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column page-content">
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <%= yield %>
    <br />
    <br />
    <%= render 'layouts/footer' %>
  </body>
</html>